### PR TITLE
feature/git-automation

### PR DESCRIPTION
**Pull request by marcoaccardi**

### CODE REVIEW

**Comment by marcoaccardi** [comment]
Screenshot 2020-04-18 at 09 44 42
@alexrodi I got this issue

**Comment by alexrodi** [comment]
@marcoaccardi I'm wondering if we should create a group/organization for this so taht we all have the same rights, what do you think?

**Comment by alexrodi** [comment]
We have these settings in Phi
Screenshot 2020-04-19 at 11 39 00

But it seems a bit dangerous to allow external actions...

**Comment by marcoaccardi** [comment]
what do you mean? Like moving this repo into another account like Pixtunes, so we can all have access?

**Comment by alexrodi** [comment]
Yes exactly  ( but please not Pixtunes! ) 😄

**Comment by marcoaccardi** [comment]
Of course! I meant just like pixtunes

**Comment by marcoaccardi** [comment]
Would you like to do that? :)

**Comment by alexrodi** [comment]
I actually enabled the first option, it's quite standard and safe...

**Comment by alexrodi** [comment]
@marcoaccardi But we should do that non-the-less, especially if people are contributing regularly, we need to establish an org (Euclid ?) 🙂

**Comment by marcoaccardi** [comment]
Awesome!

**Pull request merged**
